if(NOT DEFINED LINEAR_SOLVER_PROTO OR NOT DEFINED OPTIONAL_BOOLEAN_PROTO OR
   NOT DEFINED TEMPLATE_FILE OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "embed_proto.cmake missing required arguments.")
endif()

file(READ "${LINEAR_SOLVER_PROTO}" LINEAR_SOLVER_PROTO_TEXT)
file(READ "${OPTIONAL_BOOLEAN_PROTO}" OPTIONAL_BOOLEAN_PROTO_TEXT)

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

configure_file("${TEMPLATE_FILE}" "${OUTPUT_FILE}" @ONLY)
